export const INITIALIZE_TYPING_STORE = 'INITIALIZE_TYPING_STORE'
export const UPDATE_WORD = 'UPDATE_WORD'
export const GOTO_NEXT_WORD = 'GOTO_NEXT_WORD'
export const REFRESH_TYPING_STORE = 'REFRESH_TYPING_STORE'

const action = {
  INITIALIZE_TYPING_STORE,
  UPDATE_WORD,
  GOTO_NEXT_WORD,
  REFRESH_TYPING_STORE,
}

export default action
